---

- name: add atomix chart repo
  kubernetes.core.helm_repository:
    name: atomix
    repo_url: "https://charts.atomix.io"
  when: inventory_hostname in groups['master_nodes']

- name: add onosproject chart repo
  kubernetes.core.helm_repository:
    name: onosproject
    repo_url: "https://charts.onosproject.org"
  when: inventory_hostname in groups['master_nodes']

- name: add aether chart repo
  kubernetes.core.helm_repository:
    name: aether
    repo_url: "https://charts.aetherproject.org"
  when: inventory_hostname in groups['master_nodes']

- name: add rancher chart repo
  kubernetes.core.helm_repository:
    name: rancher
    repo_url: "http://charts.rancher.io/"
  when: inventory_hostname in groups['master_nodes']

- name: find {{ amp.data_iface }}'s subnet for RAN
  shell: ip route | grep {{ amp.data_iface }} | awk '/kernel/ {print $1}' | head -1
  register: result
  when: inventory_hostname in groups['master_nodes']
  become: true

# TODO: check if interface subnet is valid
- set_fact:
    ran_subnet: "{{ result.stdout }}"
  when: inventory_hostname in groups['master_nodes']

- name: remove /tmp/monitor-values.yaml
  file:
    path: "/tmp/monitor-values.yaml"
    state: absent
  when: inventory_hostname in groups['master_nodes']

- name: copy monitor-values.yaml to /tmp/monitor-values.yaml
  template:
    src: roles/monitor/templates/monitor-values.yaml
    dest: "/tmp/monitor-values.yaml"
  when: inventory_hostname in groups['master_nodes']

- name: deploy aether monitoring
  kubernetes.core.helm:
    update_repo_cache: true
    name: rancher-monitoring
    release_namespace: cattle-monitoring-system
    create_namespace: true
    chart_ref: "{{ amp.monitor.helm.chart_ref }}"
    chart_version: "{{ amp.monitor.helm.chart_version }}"
    values_files:
      - /tmp/monitor-values.yaml
    wait: true
    force: true
  when: inventory_hostname in groups['master_nodes']

