---

- name: remove rancher-monitoring from cattle-monitoring-system
  kubernetes.core.helm:
    name: rancher-monitoring
    release_namespace: cattle-monitoring-system
    state: absent
    wait: true
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove rancher-monitoring-crd from cattle-monitoring-system
  kubernetes.core.helm:
    name: rancher-monitoring-crd
    release_namespace: cattle-monitoring-system
    state: absent
    wait: true
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: delete namespace cattle-dashboards cattle-monitoring-system
  shell: |
    kubectl delete namespace cattle-dashboards cattle-monitoring-system
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove /tmp/monitor-values.yaml
  file:
    path: "/tmp/monitor-values.yaml"
    state: absent
  when: inventory_hostname in groups['master_nodes']
  
- name: remove openshift python package
  pip:
    name: openshift==0.12.1
    state: absent
    executable: pip3
  become: true

- name: remove python-setuptools package
  apt:
    name: python-setuptools
    state: absent
    purge: yes
  become: true

- name: remove python3-venv package
  apt:
    name: python3-venv
    state: absent
    purge: yes
  become: true

# - name: remove python3-pip package
#   apt:
#     name: python3-pip
#     state: absent
#     purge: yes
#   become: true

# - name: remove python3 package
#   apt:
#     name: python3
#     state: absent
#     purge: yes
#   become: true

- name: remove software-properties-common package
  apt:
    name: software-properties-common
    state: absent
    purge: yes
  become: true

- name: remove make package
  apt:
    name: make
    state: absent
    purge: yes
  become: true

- name: remove sshpass package
  apt:
    name: sshpass
    state: absent
    purge: yes
  become: true

- name: update cache
  apt:
    update_cache: yes
  become: true